Gtm dev
derilinx/ckanext-googleanalytics pull request #1
Opened 2024-05-02 16:09 UTC by cormachallinanderilinx

Pt.1 of GA fix - UI reporting
TODO: fix CLI

2024-05-03 09:12 UTC, jodiegardiner approved these changes

2024-05-03 09:49 UTC, saj-derilinx requested changes

2024-05-03 09:49 UTC, saj-derilinx commented on ckanext/googleanalytics/plugin/__init__.py
> +        p.toolkit.add_resource("/usr/lib/ckan-extensions/ckanext-googleanalytics/ckanext/googleanalytics/assets", "ckanext-googleanalytics")
Why is an absolute path used here?

2024-05-03 09:51 UTC, saj-derilinx commented
Is there any reason we're not syncing with the upstream repo first?
https://github.com/derilinx/ckanext-googleanalytics/compare/master...ckan%3Ackanext-googleanalytics%3Amaster

Saw this in their issues as well https://github.com/ckan/ckanext-googleanalytics/issues/69

2024-05-07 14:45 UTC, cormachallinanderilinx commented on ckanext/googleanalytics/plugin/__init__.py
> +        p.toolkit.add_resource("/usr/lib/ckan-extensions/ckanext-googleanalytics/ckanext/googleanalytics/assets", "ckanext-googleanalytics")
done

2024-05-08 09:24 UTC, merged